export const fr = {
    accountForgot: 'Forgotten password',
    accountForgotSubtitle: "Enter the e-mail that was used to register",
    add: 'Add',
    alreadyMember: 'Already a member',
    backTo: "Back to",
    changePassword: 'Change password',
    connectFB: "Connect with Facebook",
    createAccountTitle: "Create Account",
    currentPassword: 'Current password',
    code: 'Code',
    confirmPassword: 'Confirm password',  
    delete: 'Delete',  
    edit: 'Edit',
    editEmail: "Change email address",
    email: 'E-mail',
    enterCodeTitle: "Enter code",
    forgotPassword: 'Forgotten password',
    loginButton: "Login",
    loginTitle: 'Login',
    nameTitle: "Name",
    new: 'New',
    newPassword: 'New password',
    notAmember: "Not a member?",
    or: 'or',
    password: "Password",
    registerNow: "Signup",
    rememberMe: "Remember me",
    resetPassword: 'Reset password',
    signin: "Sign-in",
    signupSocial: "Connect using {0}",
    validate: 'Confirm'
}
